---
title: "Kontroller f칬r KTHs publikationscorpus"
output:
  flexdashboard::flex_dashboard:
    logo: logo.png
    favicon: favicon.ico
    vertical_layout: fill
    theme: 
      version: 5
      font-size-base: 1
      bg: "#FFF"
      fg: "#272c30" 
      primary: "#1954A6"
      navbar-bg: "#1954A6"
      base_font: 
        google: 
          family: Open Sans
          local: true
      heading_font:
        google: 
          family: Open Sans
          local: true
      code_font:
        google: 
          family: Open Sans
          local: true
---

```{r setup, include=FALSE}
library(flexdashboard)

myDT <- function(data) {
  if (is.null(data) || nrow(data) <= 0) 
    return(htmltools::pre("Denna kontroll passerar utan anm칛rkning! 游봅"))
  
  dt <- DT::datatable(data, filter = "top",
    escape = FALSE,
    rownames = FALSE,
    style = "bootstrap",
#    class = "compact",
    width = "100%",
    extensions = c(
      "Buttons",  
      "Select",
      "Scroller"
    ),
    options = list(
      dom = "fBlrtip",  # specify content (search box, etc)
#      dom = 'pt',
# l - Length changing
# f - Filtering input
# t - The Table!
# i - Information
# p - Pagination
# r - pRocessing
      scrollX = TRUE, 
      scrollY = "60vh",
      deferRender = TRUE,
      scroller = TRUE,
      select = TRUE,
      buttons = list(
        I("colvis"),  
        "csv",  
        "excel",
        list(
          extend = "copy",
          text = 'Copy to clipboard',
          exportOptions = list(modifier = list(selected = TRUE))
        )
      )  
    )
  )  
    
  htmltools::div(dt, style = "font-size:80%")
}

compact_cols <- function(data) {
  mask_keep <- colSums(!is.na(data)) > 0
  data[, mask_keep, drop = FALSE]
}

```

Resultat  {data-icon="fa-table"}
=============================

Kontroller {.tabset .tabset-pills .tabset-fade}
-------------------------

### Titelmultipletter

```{r}
library(kthcorpus)
library(dplyr)

checks <- kth_diva_checks()

myDT(checks$article_title_multiplettes)
```

### Publiceringsstatus

```{r}
myDT(checks$submission_status_invalid %>% select(-c(Name, Abstract)) %>% compact_cols())
```

### Saknade kthid:n

```{r}
myDT(checks$missing_kthid)
```

<!-- TODO: ska detta vara med? f칬r alla publikationer?
### Saknade 친r/publiceringsdatum i DiVA

```{r}
myDT(checks$missing_date)
```
-->

### Saknade ISSN

```{r}
myDT(checks$missing_journal_ids  %>% select(-c(Name, Abstract)) %>% compact_cols())
```

### DOI-multipletter

```{r}
myDT(checks$multiplettes_DOI %>% select(DOI_link, everything()) %>% select(-c("DOI")))
```

### ScopusID-multipletter

```{r}
myDT(checks$multiplettes_scopusid)
```

### ISI-multipletter

```{r}
myDT(checks$multiplettes_ISI)
```


### Ogiltig ISI

```{r}
myDT(checks$invalid_ISI)
```

### Ogiltig DOI

```{r}
myDT(checks$invalid_DOI)
```

### Ogiltig ISSN

```{r}
myDT(checks$invalid_ISSN)
```

### Ogiltig organisationstillh칬righet

```{r}
myDT(checks$invalid_orgid)
```

### Oklar publikationsstatus

```{r}
myDT(checks$uncertain_published)
```

### SwePubs kontroller

```{r}
myDT(swepub_checks())
```

Information {data-icon="fa-info-circle"}
========================================

About
--------------------

### Information 

Denna sammanst칛llning gjordes `r Sys.time()` och inneh친ller resultat fr친n kontroller gjorda p친 KTHs publikationsm칛ngd som laddades ned fr친n DiVA-portalen.

Datak칛llorna som anv칛ndes vid kontrollerna har f칬ljande tidsst칛mplar:

```{r}

knitr::kable(diva_meta())

```

